<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>articleTitle</name>
   <tag></tag>
   <elementGuidId>e3d35be4-ff3c-4662-806b-1028a94f275e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,'txtTitle')][contains(@class,'txtTitle')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,'txtTitle')][contains(@class,'txtTitle')]</value>
   </webElementProperties>
</WebElementEntity>
