<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pubInfoTab</name>
   <tag></tag>
   <elementGuidId>0367b1c8-2826-4940-afb4-dc4e165e0d35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@id,'_tbhTabbedRendertag0')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@id,'_tbhTabbedRendertag0')]</value>
   </webElementProperties>
</WebElementEntity>
