<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>publicInfo</name>
   <tag></tag>
   <elementGuidId>dd73b77c-8aab-4662-9463-831272cae686</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id,'param_public')]//iframe[contains(@id,'txtContent_textarea')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id,'param_public')]//iframe[contains(@id,'txtContent_textarea')]</value>
   </webElementProperties>
</WebElementEntity>
